# If you see me, please update my `rev` field using the provided links
# Click the repo and update to latest tags.
# If things break on update, raise an issue
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort imports deepcave
        files: deepcave

      - id: isort
        name: isort imports tests
        files: tests

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black formatter deepcave
        files: deepcave

      - id: black
        name: black formatter tests
        files: tests

      - id: black
        name: black formatter examples
        files: examples

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: deepcave
        additional_dependencies: ["tomli"] # Needed to parse pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        name: mypy deepcave
        files: deepcave
        args: ["--check-untyped-defs", "--install-types", "--non-interactive", "--ignore-missing-imports"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 deepcave
        files: deepcave

      - id: flake8
        name: flake8 tests
        files: tests
