version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  deep_cave.store:
    level: DEBUG
    handlers: [console]
    propagate: no
  deep_cave.registry:
    level: DEBUG
    handlers: [ console ]
    propagate: no
  deep_cave.server:
    level: DEBUG
    handlers: [console]
    propagate: no
  deep_cave.util:
    level: DEBUG
    handlers: [ console ]
    propagate: no
  deep_cave.logger:
    level: DEBUG
    handlers: [ console ]
    propagate: no
  deep_cave.converter:
    level: DEBUG
    handlers: [ console ]
    propagate: no
  deep_cave.storage_backend:
    level: DEBUG
    handlers: [ console ]
    propagate: no
  matplotlib:
    level: INFO
    handlers: [ console ]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
